modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="alchemy_construct"
version="1.0.0"
displayName="Alchemy Construct"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="yujing, MCreator"

[[dependencies.alchemy_construct]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




